name: Email Sender

on:
  push:
    branches:
      - main

jobs:
  email-sender:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install python-dotenv

      - name: Run Python script
        env:
          RECEIVER1: ${{ secrets.RECEIVER1 }}
          SENDER: ${{ secrets.SENDER }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python email_sender.py
